image: registry.gitlab.com/ignitionrobotics/web/images/kubectl:latest

stages:
- deploy

# Replaces all env vars inside YML/YAML files.
# .gitlab-ci.yml is not affected
.replace_env_vars: &replace_env_vars
  - >-
    find . -regex '.\+\.ya\?ml' \
           -not -name '.gitlab-ci.yml' \
           -exec sh -c 'echo "$(envsubst < {})" > {}' \;

# Deploys to a Kubernetes cluster.
#  must be set before calling this.
.deploy_kubernetes: &deploy_kubernetes
  - *replace_env_vars

deploy_staging:
  stage: deploy
  script:
  - . ./overlays/staging/staging.env
  - *deploy_kubernetes
  - cat base/namespace.yaml
#  tags:
#  - kubernetes
#  - staging
#
#deploy_production:
#  stage: deploy
#  script:
#  - *deploy_kubernetes
#  tags:
#  - kubernetes
#  - stagingr