image: registry.gitlab.com/ignitionrobotics/web/images/kubectl:latest

stages:
- deploy

# Replaces all env vars inside YML/YAML files.
# .gitlab-ci.yml is not affected
.replace_env_vars: &replace_env_vars
  - >-
    find . -iregex '.+\.ya?ml' -not -iname '.gitlab-ci.yaml'
    -exec sh -c '
        echo = {} =;
        envsubst < {} | \
        tee {}; echo "\n"' \;

# Deploys to a Kubernetes cluster.
#  must be set before calling this.
.deploy_kubernetes: &deploy_kubernetes
  - *replace_env_vars

deploy_staging:
  stage: deploy
  script:
  - pwd
  - ls
  - source ./overlays/staging.staging.env
  - env
#  - find . -regex '.+\.ya?ml' -not -iname '.gitlab-ci.yaml' -exec sh -c ' echo = {} =; envsubst < {} | \ tee {}; echo "\n"' \;
#  - *deploy_kubernetes
#  tags:
#  - kubernetes
#  - staging
#
#deploy_production:
#  stage: deploy
#  script:
#  - *deploy_kubernetes
#  tags:
#  - kubernetes
#  - stagingr