image: registry.gitlab.com/ignitionrobotics/web/images/kubectl:latest

stages:
- deploy

# Replaces all env vars inside YML/YAML files.
# .gitlab-ci.yml is not affected
.replace_env_vars: &replace_env_vars
  - >-
    find . -regex '.\+\.ya\?ml' \
           -not -name '.gitlab-ci.yml' \
           -exec sh -c 'echo "$(envsubst < {})" > {}' \;

# Deploys to a Kubernetes cluster.
# OVERLAY must be set to the overlay directory name containing the target kustomization.yaml file before calling this.
.deploy_kubernetes: &deploy_kubernetes
  - . ./overlays/${OVERLAY}/${OVERLAY}.env
  - export KUSTOMIZE_TARGET=./overlays/${OVERLAY}
  - *replace_env_vars
  - kubectl apply -k ${KUSTOMIZE_TARGET}

deploy_staging:
  stage: deploy
  script:
  - export OVERLAY=staging
  - *deploy_kubernetes
  environment:
    name: staging
  tags:
  - kubernetes
  - staging
  when: manual

deploy_production:
  stage: deploy
  script:
  - export OVERLAY=production
  - *deploy_kubernetes
  tags:
  - kubernetes
  - production